### ISSUE TITLE
Provide beta release?

### ISSUE THREAD

**Issue by kuhnroyal** [ngxs-labs/entity-state#127]
We are using this in a project close to production and are currently building this ourselves.
Is it possible to provide it as NPM package with beta/alpha tag?

**Comment by kuhnroyal** [comment]
Or provide a npm 5 prepare script for installing non-published references.

**Comment by JanMalch** [comment]
@eranshmil you added build & publish utils. Can you help out?

**Comment by philly-vanilly** [comment]
Sorry for the "+1" type of comment, but I also wanted to express that this would be very helpful. I will go into freelancing soon after having worked with Angular for years and having tried out different types of state management. And to my future clients I could only recommend NGXS over NGRX, if NGXS had a working solution for entity-management. In my current project almost everything is an entity, so for enterprise applications this is a dealbreaker.

I tried out the lib in its current state and even if you need some workarounds, you can definitely already work with it. So having it on NPM over copy-pasting code from GitHub would be a huge improvement.

If you can't release it now for some reason, please at least provide some sort of a roadmap/estimation when it's gonna be published. For businesses information like this is important.

**Comment by JanMalch** [comment]
When issue #85 is closed only minor things like documentation (#5) remain and the library could be released.
Unfortunately is development is halted, as I am busy with urgent projects and @markwhitfeld is working on v3.5 of ngxs/store. I hope to close #85 within the next 3-4 weeks.
Sorry for the inconvience.

---

>you need some workarounds

Feel free to open feature requests. This library is included in the [official 4.0.0 milestone](https://github.com/ngxs/store/milestone/4?closed=1) and mentioned in the [state-operator blog post](https://medium.com/ngxs/ngxs-state-operators-8b339641b220) so it's highly unlikely that it will be abandoned and the issues are useful for the future, even if they might not be included in the very near future (depends on the issue)

**Comment by philly-vanilly** [comment]
@JanMalch Thanks for info! Really appreciate your work on this lib. The workarounds I mentioned are for the issues that are open already, in particular the one concerning developmentMode.

**Comment by kuhnroyal** [comment]
I forked this and replaced yarn with NPM in the build script.
I added a NPM prepare script.

Now you can install it with NPM and have NPM build it locally after install.

```
"@ngxs-labs/entity-state": "github:kuhnroyal/entity-state#dfc3a375371de2f83d5710f2cef1c28975a3ba56"
```
Adding this with the branch should also work but in my tests it sometimes was not the latest commit.
```
"@ngxs-labs/entity-state": "github:kuhnroyal/entity-state#feature/npm-prepare"
```
https://github.com/kuhnroyal/entity-state/tree/feature/npm-prepare

I only got this to work with NPM, it is supposed to also work with yarn but I couldn't get it to work.

**Comment by splincode** [comment]
Hi guys, I published current package with version 0.0.1 from master

https://www.npmjs.com/package/@ngxs-labs/entity-state

**Comment by vojtesaak** [comment]
@splincode hello, could you please update npm package with current master ?

**Comment by cblaettl** [comment]
I think this package is really important for many people working with ngxs or thinking about transitioning to ngxs. So big thanks for the work so far. <3

@splincode Since this package didn't get too much love in the last couple of months, I'd suggest adding an [install hook, that builds the package](https://stackoverflow.com/a/48429738).
That would allow to easily install the package directly from GitHub, without having to worry about building the package or forking it.

Let me know if that's a stupid idea. ;) Otherwise I'm really looking forward to a proper release!

**Comment by splincode** [comment]
I'm working on entity management now
https://github.com/ngxs-labs/data

**Comment by guitarooman14** [comment]
Hi guys,
I'm really expecting to test this feature that I was alrady using on NGRX but I'm still facing to the issue [65f2d55](https://github.com/ngxs-labs/entity-state/commit/65f2d553099c08d8f5404fbac3f6c28911631f3c) that has been fixed on 18 Mar 2019. I think the version deployed on npm is not the last one so if you can do so, it would be nice.

**Comment by JanMalch** [comment]
Hi, I don't know why this fix wasn't included in 0.0.1 as the fix was in master 3 months earlier.
I currently want to make another release to also publish the fix for #206 but I'm having technical issues publishing it.

**Comment by guitarooman14** [comment]
@JanMalch Any updates?

**Comment by guitarooman14** [comment]
> Hi, I don't know why this fix wasn't included in 0.0.1 as the fix was in master 3 months earlier.
> I currently want to make another release to also publish the fix for #206 but I'm having technical issues publishing it.

@JanMalch any updates?

**Comment by JanMalch** [comment]
I just published 0.0.2
Let me know if everything works

**Comment by Frankitch** [comment]
Hi @JanMalch Are you still working on this? Is it safe to use in production? This plugin adresses perfectly my needs and matches existing features on Akita or NGRX.
This woud be awesome to get a stable release!
